version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true

image: Ubuntu2204

install:
  - source $HOME/venv3.11.8/bin/activate
  - pip install -r requirements.txt

test_script:
  - export PYTHONPATH=$PYTHONPATH:'.'
  - python -m unittest discover -s tests

deploy_script:
  - python setup.py sdist

